//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductСomposition
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> ingredient_id { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Products Products { get; set; }
    }
}
