//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int id { get; set; }
        public string title_of_role { get; set; }
        public string role_email { get; set; }
        public string role_password { get; set; }
    }
}
